// Copyright 2025 Circle Internet Group, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::path::PathBuf;

use clap::Args;

use crate::{
    accounts::PartitionMode,
    config::{Erc20FnWeights, GuzzlerFnWeights, TxTypeMix},
    Config,
};

/// Default values shared between clap attrs and `to_cli_args` to prevent drift.
pub(crate) mod defaults {
    use std::time::Duration;

    pub const NUM_GENERATORS: usize = 1;
    pub const MAX_NUM_ACCOUNTS: usize = 100;
    pub const NUM_TXS: u64 = 0;
    pub const RATE: u64 = 1000;
    pub const TIME: u64 = 0;
    pub const TX_INPUT_SIZE: usize = 0;
    pub const MAX_TXS_PER_ACCOUNT: u64 = 0;
    pub const RECONNECT_ATTEMPTS: u32 = 3;
    pub const RECONNECT_PERIOD: Duration = Duration::from_secs(3);
    /// Mirror of `RECONNECT_PERIOD` in the form clap's `default_value` accepts.
    pub const RECONNECT_PERIOD_STR: &str = "3s";
}

#[derive(Debug, Clone, PartialEq, Eq, Args)]
pub struct SpammerArgs {
    /// Number of transaction generators to run in parallel
    ///
    /// A higher number of generators helps increase the transaction rate.
    /// Each generator will manage a subset of the accounts, so there won't
    /// be nonce collisions generated by different generators.
    #[clap(short = 'g', long, default_value_t = defaults::NUM_GENERATORS, global = true)]
    pub num_generators: usize,
    /// Maximum number of genesis accounts used to sign transactions
    ///
    /// The number of accounts in the genesis file must be equal or higher
    /// than this number. A higher value helps decrease the risk of nonce
    /// gaps. The genesis file must be generated with a sufficient number of
    /// extra prefunded accounts. Check out the `--num-extra-accounts`
    /// argument of the `setup` command.
    #[clap(short = 'a', long, default_value_t = defaults::MAX_NUM_ACCOUNTS, global = true)]
    pub max_num_accounts: usize,
    /// How to partition the account space among generators (linear or
    /// exponential)
    ///
    /// Linear mode: the space is divided equally between generators.
    ///
    /// Exponential mode: each generator takes half of the unassigned space
    /// until there's no more space unassigned. The generator with the
    /// higher number of the accounts will reuse the same account less
    /// often, thus reducing the probability of having nonce conflicts for
    /// those accounts. Generators handling a small range of accounts will
    /// reuse those accounts very frequently, thus reaching higher nonce
    /// values for those accounts.
    #[clap(
        short = 'm',
        long,
        value_enum,
        default_value_t = PartitionMode::Linear,
        global = true
    )]
    pub partition_mode: PartitionMode,
    /// Maximum total number of transactions to send (0 for no limit)
    #[clap(short = 'n', long, default_value_t = defaults::NUM_TXS, global = true)]
    pub num_txs: u64,
    /// Number of transactions to send per second (all generators combined)
    #[clap(short = 'r', long, default_value_t = defaults::RATE, global = true, value_parser = clap::value_parser!(u64).range(1..))]
    pub rate: u64,
    /// Closed-loop pool governor: pause sending while the target node's txpool
    /// depth (pending + queued) exceeds this many transactions. 0 = open loop.
    /// Over-offering past what the chain consumes collapses the pool (eviction
    /// nonce-gaps accounts); target ~2-3 blocks' worth of transactions.
    #[clap(long, default_value_t = 0, global = true)]
    pub pool_target: u64,
    /// Maximum time in seconds to send transactions (applies to all generators) (0 for no limit)
    #[clap(short = 't', long, default_value_t = defaults::TIME, global = true)]
    pub time: u64,
    /// Size of transaction input data in bytes
    #[clap(short = 's', long, default_value_t = defaults::TX_INPUT_SIZE, global = true)]
    pub tx_input_size: usize,
    /// Every transfer pays a brand-new recipient address (creates a new account per tx)
    #[clap(long, default_value_t = false, global = true)]
    pub fresh_recipients: bool,
    /// Recipient pool "base:size" (e.g. 0x100000000:10000000): sequential walk with wrap —
    /// first pass creates the accounts, later passes are pure balance updates (takes precedence
    /// over --fresh-recipients)
    #[clap(long, global = true)]
    pub recipient_pool: Option<String>,
    /// Maximum number of transactions to send per account (0 for no limit)
    ///
    /// A low value helps reduce the risk of nonce gaps. A high value will
    /// take more time to initialise accounts.
    #[clap(short = 'x', long, default_value_t = defaults::MAX_TXS_PER_ACCOUNT, global = true)]
    pub max_txs_per_account: u64,
    /// Pre-initialize accounts with their signing keys and latest nonces
    /// (default is to lazily initialize each account).
    ///
    /// By default, each account is initialised on the fly just before
    /// sending the first transaction, which reduces the transaction rate.
    #[clap(short = 'i', long, default_value = "false", global = true)]
    pub preinit_accounts: bool,
    /// Whether to query nodes for the latest nonce of each account before sending the first transaction (may choke RPC endpoints) or start from nonce=0 (faster).
    ///
    /// Finding out the latest nonce of an account requires one RPC call to each target node.
    #[clap(short = 'l', long, default_value = "false", global = true)]
    pub query_latest_nonce: bool,
    /// Output the status of all Reth tx-pools (number of pending and queued transactions)
    #[clap(
        short = 'p',
        long,
        default_value = "false",
        visible_alias = "pools",
        global = true
    )]
    pub show_pool_status: bool,
    /// Record submit-to-finalized latency to a CSV file.
    ///
    /// This mode records the time when a transaction is submitted via
    /// `eth_sendRawTransaction` and the time when it is observed in a
    /// block via `eth_subscribe("newHeads")`.
    #[clap(long, default_value = "false", global = true)]
    pub tx_latency: bool,
    /// Directory for the latency CSV file.
    ///
    /// Defaults to the current directory when omitted.
    /// Can only be used when `--tx-latency` is enabled.
    #[clap(long, requires = "tx_latency", global = true)]
    pub csv_dir: Option<PathBuf>,
    /// Wait for the response from Reth after sending a transaction
    ///
    /// If false, the output will only show the number of transactions sent and its length in bytes.
    /// If true, the output will additionally show error messages if any, but it will slow down the execution.
    #[clap(short = 'w', long, default_value = "false", global = true)]
    pub wait_response: bool,
    /// Number of reconnection attempts when a connection fails
    #[clap(long, default_value_t = defaults::RECONNECT_ATTEMPTS, global = true)]
    pub reconnect_attempts: u32,
    /// Time to wait between reconnection attempts (e.g., "3s", "500ms")
    #[clap(
        long,
        default_value = defaults::RECONNECT_PERIOD_STR,
        value_parser = humantime::parse_duration,
        global = true
    )]
    pub reconnect_period: std::time::Duration,
    /// Weighted transaction type mix.
    ///
    /// Format: transfer=50,legacy=20,erc20=20,guzzler=10
    /// Omitted types default to weight 0 (disabled).
    /// When omitted, defaults based on --guzzler-fn-weights:
    ///   if guzzler functions enabled: 100% guzzler;
    ///   otherwise: 100% transfer.
    #[clap(long = "mix", global = true)]
    pub tx_type_mix: Option<TxTypeMix>,
    /// Weighted function mix and per-function argument for GasGuzzler calls.
    ///
    /// Format: hash-loop=70@2000,storage-write=30@600,storage-read=0,guzzle=0,guzzle2=0
    /// Omitted functions default to weight 0 (disabled), so "hash-loop=100@2000" is valid.
    /// If total weight is 0, transfer transactions are used.
    #[clap(
        long = "guzzler-fn-weights",
        default_value = "hash-loop=0,storage-write=0,storage-read=0,guzzle=0,guzzle2=0",
        global = true
    )]
    pub guzzler_fn_weights: GuzzlerFnWeights,
    /// Weighted function mix for ERC-20 calls.
    ///
    /// Format: transfer=70,approve=20,transfer-from=10
    /// Omitted functions default to weight 0 (disabled).
    /// When omitted (all weights 0), ERC-20 uses 100% transfer.
    #[clap(long = "erc20-fn-weights", global = true)]
    pub erc20_fn_weights: Option<Erc20FnWeights>,
}

impl SpammerArgs {
    /// Serialize these arguments back to CLI flag format suitable for passing
    /// to the remote `spammer.sh` script (or any process that accepts the
    /// same clap interface).
    ///
    /// Only emits flags that differ from the clap defaults so the resulting
    /// command stays concise.
    pub fn to_cli_args(&self) -> Vec<String> {
        let mut args = Vec::new();

        /// Emit a valued flag when the field differs from its default.
        macro_rules! flag {
            ($args:ident, $flag:expr, $val:expr, $default:expr) => {
                if $val != $default {
                    $args.extend([$flag.to_string(), $val.to_string()]);
                }
            };
        }

        /// Emit a boolean flag when the field is true.
        macro_rules! bool_flag {
            ($args:ident, $flag:expr, $val:expr) => {
                if $val {
                    $args.push($flag.to_string());
                }
            };
        }

        flag!(args, "-g", self.num_generators, defaults::NUM_GENERATORS);
        flag!(
            args,
            "-a",
            self.max_num_accounts,
            defaults::MAX_NUM_ACCOUNTS
        );
        if self.partition_mode != PartitionMode::Linear {
            args.extend(["-m".to_string(), "exponential".to_string()]);
        }
        flag!(args, "-n", self.num_txs, defaults::NUM_TXS);
        flag!(args, "-r", self.rate, defaults::RATE);
        flag!(args, "--pool-target", self.pool_target, 0);
        flag!(args, "-t", self.time, defaults::TIME);
        flag!(args, "-s", self.tx_input_size, defaults::TX_INPUT_SIZE);
        flag!(
            args,
            "-x",
            self.max_txs_per_account,
            defaults::MAX_TXS_PER_ACCOUNT
        );

        bool_flag!(args, "-i", self.preinit_accounts);
        bool_flag!(args, "-l", self.query_latest_nonce);
        bool_flag!(args, "-p", self.show_pool_status);
        bool_flag!(args, "--tx-latency", self.tx_latency);
        bool_flag!(args, "-w", self.wait_response);

        flag!(
            args,
            "--reconnect-attempts",
            self.reconnect_attempts,
            defaults::RECONNECT_ATTEMPTS
        );
        if self.reconnect_period != defaults::RECONNECT_PERIOD {
            args.extend([
                "--reconnect-period".to_string(),
                humantime::format_duration(self.reconnect_period).to_string(),
            ]);
        }

        /// Collect `name=value` pairs from fields, emitting a compound flag.
        macro_rules! weight_flag {
            ($args:ident, $flag:expr, [$(($name:expr, $val:expr)),+ $(,)?]) => {{
                let parts: Vec<String> = [$(($name, $val)),+]
                    .iter()
                    .filter(|(_, v)| *v > 0)
                    .map(|(name, v)| format!("{}={}", name, v))
                    .collect();
                if !parts.is_empty() {
                    $args.extend([$flag.to_string(), parts.join(",")]);
                }
            }};
        }

        if let Some(ref mix) = self.tx_type_mix {
            weight_flag!(
                args,
                "--mix",
                [
                    ("transfer", mix.transfer),
                    ("legacy", mix.legacy),
                    ("erc20", mix.erc20),
                    ("guzzler", mix.guzzler),
                ]
            );
        }
        if self.guzzler_fn_weights.total_weight() > 0 {
            let w = &self.guzzler_fn_weights;
            let parts: Vec<String> = [
                ("hash-loop", w.hash_loop),
                ("storage-write", w.storage_write),
                ("storage-read", w.storage_read),
                ("guzzle", w.guzzle),
                ("guzzle2", w.guzzle2),
            ]
            .iter()
            .filter(|(_, c)| c.weight > 0)
            .map(|(name, c)| format!("{}={}@{}", name, c.weight, c.arg))
            .collect();
            if !parts.is_empty() {
                args.extend(["--guzzler-fn-weights".to_string(), parts.join(",")]);
            }
        }
        if let Some(ref erc20) = self.erc20_fn_weights {
            weight_flag!(
                args,
                "--erc20-fn-weights",
                [
                    ("transfer", erc20.transfer),
                    ("approve", erc20.approve),
                    ("transfer-from", erc20.transfer_from),
                ]
            );
        }

        args
    }

    pub fn to_config(&self, silent: bool, fire_and_forget: bool) -> Config {
        // Resolve tx_type_mix: explicit --mix takes precedence, otherwise
        // infer from --guzzler-fn-weights for backward compatibility.
        let tx_type_mix = self.tx_type_mix.unwrap_or_else(|| {
            if self.guzzler_fn_weights.total_weight() > 0 {
                TxTypeMix {
                    guzzler: 100,
                    ..Default::default()
                }
            } else {
                TxTypeMix {
                    transfer: 100,
                    ..Default::default()
                }
            }
        });

        // Resolve erc20_fn_weights: explicit --erc20-fn-weights takes precedence, otherwise
        // default to 100% transfer for backward compatibility.
        let erc20_fn_weights = self.erc20_fn_weights.unwrap_or(Erc20FnWeights {
            transfer: 100,
            ..Default::default()
        });

        Config {
            num_generators: self.num_generators,
            partition_mode: self.partition_mode,
            max_num_accounts: self.max_num_accounts,
            preinit_accounts: self.preinit_accounts,
            query_latest_nonce: self.query_latest_nonce,
            max_num_txs: self.num_txs,
            max_rate: self.rate,
            pool_target: self.pool_target,
            max_time: self.time,
            tx_input_size: self.tx_input_size,
            fresh_recipients: self.fresh_recipients,
            recipient_pool: self.recipient_pool.as_ref().map(|v| {
                let (b, z) = v.split_once(':').expect("--recipient-pool needs base:size");
                let parse = |x: &str| -> u64 {
                    if let Some(h) = x.strip_prefix("0x") { u64::from_str_radix(h, 16).unwrap() }
                    else { x.parse().unwrap() }
                };
                (parse(b), parse(z))
            }),
            max_txs_per_account: self.max_txs_per_account,
            silent,
            show_pool_status: self.show_pool_status,
            tx_latency: self.tx_latency,
            wait_response: self.wait_response,
            reconnect_attempts: self.reconnect_attempts,
            reconnect_period: self.reconnect_period,
            tx_type_mix,
            guzzler_fn_weights: self.guzzler_fn_weights,
            erc20_fn_weights,
            csv_dir: self.csv_dir.clone(),
            fire_and_forget,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{GuzzlerFnConfig, GuzzlerFnWeights, TxTypeMix};

    fn default_args() -> SpammerArgs {
        SpammerArgs {
            num_generators: defaults::NUM_GENERATORS,
            max_num_accounts: defaults::MAX_NUM_ACCOUNTS,
            partition_mode: PartitionMode::Linear,
            num_txs: defaults::NUM_TXS,
            rate: defaults::RATE,
            pool_target: 0,
            time: defaults::TIME,
            tx_input_size: defaults::TX_INPUT_SIZE,
            fresh_recipients: false,
            recipient_pool: None,
            max_txs_per_account: defaults::MAX_TXS_PER_ACCOUNT,
            preinit_accounts: false,
            query_latest_nonce: false,
            show_pool_status: false,
            tx_latency: false,
            csv_dir: None,
            wait_response: false,
            reconnect_attempts: defaults::RECONNECT_ATTEMPTS,
            reconnect_period: defaults::RECONNECT_PERIOD,
            tx_type_mix: None,
            guzzler_fn_weights: GuzzlerFnWeights::default(),
            erc20_fn_weights: None,
        }
    }

    #[test]
    fn to_cli_args_defaults_produces_empty() {
        let args = default_args();
        assert!(args.to_cli_args().is_empty());
    }

    #[test]
    fn to_cli_args_non_default_values() {
        let args = SpammerArgs {
            rate: 200,
            time: 60,
            num_generators: 4,
            preinit_accounts: true,
            ..default_args()
        };
        let cli = args.to_cli_args();

        let g_idx = cli.iter().position(|a| a == "-g").unwrap();
        assert_eq!(cli[g_idx + 1], "4");
        let r_idx = cli.iter().position(|a| a == "-r").unwrap();
        assert_eq!(cli[r_idx + 1], "200");
        let t_idx = cli.iter().position(|a| a == "-t").unwrap();
        assert_eq!(cli[t_idx + 1], "60");
        assert!(cli.contains(&"-i".to_string()));
    }

    #[test]
    fn to_cli_args_with_mix() {
        let args = SpammerArgs {
            tx_type_mix: Some(TxTypeMix {
                transfer: 70,
                erc20: 30,
                ..Default::default()
            }),
            ..default_args()
        };
        let cli = args.to_cli_args();
        assert!(cli.contains(&"--mix".to_string()));
        let mix_idx = cli.iter().position(|a| a == "--mix").unwrap();
        let mix_val = &cli[mix_idx + 1];
        assert!(mix_val.contains("transfer=70"));
        assert!(mix_val.contains("erc20=30"));
    }

    #[test]
    fn to_cli_args_with_guzzler_weights() {
        let args = SpammerArgs {
            guzzler_fn_weights: GuzzlerFnWeights {
                hash_loop: GuzzlerFnConfig {
                    weight: 100,
                    arg: 2000,
                },
                ..Default::default()
            },
            ..default_args()
        };
        let cli = args.to_cli_args();
        assert!(cli.contains(&"--guzzler-fn-weights".to_string()));
        let idx = cli
            .iter()
            .position(|a| a == "--guzzler-fn-weights")
            .unwrap();
        assert_eq!(cli[idx + 1], "hash-loop=100@2000");
    }

    #[test]
    fn reconnect_period_default_is_consistent() {
        assert_eq!(
            humantime::parse_duration(defaults::RECONNECT_PERIOD_STR).unwrap(),
            defaults::RECONNECT_PERIOD,
        );
    }

    #[test]
    fn to_cli_args_subsecond_reconnect_period() {
        let args = SpammerArgs {
            reconnect_period: std::time::Duration::from_millis(500),
            ..default_args()
        };
        let cli = args.to_cli_args();
        let idx = cli.iter().position(|a| a == "--reconnect-period").unwrap();
        assert_eq!(cli[idx + 1], "500ms");
    }

    #[test]
    fn to_cli_args_roundtrip() {
        use clap::Parser;

        #[derive(Parser)]
        struct TestCli {
            #[command(flatten)]
            args: SpammerArgs,
        }

        let original = TestCli::parse_from([
            "spammer",
            "-r",
            "200",
            "-g",
            "4",
            "-i",
            "--reconnect-period",
            "500ms",
            "--mix",
            "transfer=70,erc20=30",
        ])
        .args;

        let mut argv = vec!["spammer".to_string()];
        argv.extend(original.to_cli_args());
        let reparsed = TestCli::parse_from(argv).args;

        assert_eq!(reparsed, original);
    }
}
