// Copyright 2026 Circle Internet Group, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#![allow(
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    clippy::unwrap_used
)]

use std::{collections::HashMap, fs, io::IsTerminal};

use clap::{Parser, Subcommand};
use clap_verbosity_flag::{InfoLevel, Verbosity};
use color_eyre::eyre::{self, Context, Result};
use serde::Deserialize;
use tracing_subscriber::EnvFilter;
use url::Url;

use spammer::{Spammer, SpammerArgs};

const DEFAULT_WS_TARGET: &str = "127.0.0.1:8546";

#[derive(Parser)]
#[command(
    name = "spammer",
    version = arc_version::SHORT_VERSION,
    long_version = arc_version::LONG_VERSION,
    about = "Spammer: transaction load generator and sender"
)]
struct Cli {
    /// Seed for deterministic execution
    #[arg(long, global = true)]
    seed: Option<u64>,
    /// Use fire-and-forget mode: push transactions into a buffered channel
    /// and send without waiting for responses. Nonces are incremented
    /// optimistically. By default the spammer uses backpressure mode.
    #[arg(long, default_value = "false", global = true)]
    fire_and_forget: bool,
    /// Spammer configuration
    #[command(flatten)]
    args: SpammerArgs,

    #[command(flatten)]
    verbosity: Verbosity<InfoLevel>,

    /// Target selection mode
    #[command(subcommand)]
    command: TargetCommand,
}

#[derive(Subcommand, Debug, Clone)]
enum TargetCommand {
    /// Target nodes by directly specifying their WebSocket endpoints
    #[command(
        after_long_help = "Examples:\n  spammer ws\n  spammer ws --targets ws://127.0.0.1:8546,ws://127.0.0.1:9546\n"
    )]
    Ws {
        /// Explicit targets for this command.
        #[arg(long, value_delimiter = ',')]
        targets: Option<Vec<String>>,
    },
    /// Target nodes by name, using a nodes metadata file.
    ///
    /// If no node names are provided, all nodes from the file are used.
    #[command(
        after_long_help = "Examples:\n  spammer nodes --nodes-path some/path/nodes.json\n  spammer nodes --nodes-path some/path/nodes.json --targets validator1,validator2\n"
    )]
    Nodes {
        /// File with node metadata used to resolve node names to WebSocket
        /// endpoints.
        /// You can look at the .quake/<testnet-name>/nodes.json file to understand
        /// the format of the nodes metadata file. This file is generated by the
        /// `quake setup` command.
        #[arg(short = 'f', long, required = true)]
        nodes_path: String,
        /// Explicit targets for this command.
        #[arg(long, value_delimiter = ',')]
        targets: Option<Vec<String>>,
    },
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();

    // Lane routing: sign txs with the target lane's chainId (default 1337).
    spammer::set_chain_id(cli.args.chain_id);

    // Initialize tracing
    let level = cli.verbosity.tracing_level_filter();
    let filter = EnvFilter::builder()
        .with_default_directive(level.into())
        .from_env()?
        .add_directive("hyper_util::client=info".parse()?)
        .add_directive("arc_node_consensus_cli::new=info".parse()?);
    let subscriber = tracing_subscriber::fmt()
        .with_max_level(level)
        .with_ansi(std::io::stdout().is_terminal())
        .with_env_filter(filter)
        .finish();

    tracing::subscriber::set_global_default(subscriber)
        .context("Failed to set tracing subscriber")?;

    tracing::info!(
        version = arc_version::GIT_VERSION,
        commit = arc_version::GIT_COMMIT_HASH,
        "Spammer starting"
    );

    let config = cli
        .args
        .to_config(cli.verbosity.is_silent(), cli.fire_and_forget);
    config.validate()?;

    // Build the WebSocket URLs of the target nodes
    let target_ws_urls = match cli.command {
        TargetCommand::Ws { targets } => {
            let target_nodes = targets.unwrap_or_else(|| vec![DEFAULT_WS_TARGET.to_string()]);
            ws_urls_from_strings(target_nodes)
        }
        TargetCommand::Nodes {
            nodes_path,
            targets,
        } => {
            let target_nodes = targets.unwrap_or_default();
            ws_urls_from_file(&nodes_path, target_nodes)?
        }
    };

    let spammer = Spammer::new(target_ws_urls, &config).await?;
    spammer.run().await?;

    Ok(())
}

// Build the WebSocket URLs of the target nodes from the list of IP addresses and ports
fn ws_urls_from_strings(target_nodes: Vec<String>) -> Vec<(String, Url)> {
    target_nodes
        .into_iter()
        .map(|s| (s.clone(), ws_url_from_str(s)))
        .collect()
}

fn ws_url_from_str(ip_port: String) -> Url {
    let url_str = if !ip_port.starts_with("ws://") {
        format!("ws://{ip_port}")
    } else {
        ip_port
    };
    Url::parse(&url_str).unwrap()
}

// Read the file with node metadata and obtain the WebSocket URLs of the target nodes
fn ws_urls_from_file(nodes_path: &str, target_nodes: Vec<String>) -> Result<Vec<(String, Url)>> {
    let nodes_metadata = fs::read_to_string(nodes_path)
        .map_err(|e| eyre::eyre!("Failed to read {nodes_path}: {e}"))?;
    let nodes_metadata = serde_json::from_str::<Vec<NodeMetadata>>(&nodes_metadata)?;

    // If no target nodes are provided, use all nodes from the file.
    if target_nodes.is_empty() {
        let result: Vec<(String, Url)> = nodes_metadata
            .into_iter()
            .map(|node| (node.name.clone(), node.execution.ws_url.clone()))
            .collect();
        return Ok(result);
    }

    // Otherwise, validate that all requested names exist in the metadata file.
    // Return an error on the first missing name.
    let nodes_map: HashMap<&str, &NodeMetadata> = nodes_metadata
        .iter()
        .map(|n| (n.name.as_str(), n))
        .collect();

    let mut result = Vec::with_capacity(target_nodes.len());
    for name in target_nodes {
        match nodes_map.get(name.as_str()) {
            Some(node) => result.push((name, node.execution.ws_url.clone())),
            None => eyre::bail!("Target node not found in metadata file {nodes_path}: {name}"),
        }
    }

    Ok(result)
}

#[derive(Deserialize, Clone, Debug)]
struct NodeMetadata {
    name: String,
    execution: ExecutionContainer,
}

#[derive(Deserialize, Clone, Debug)]
struct ExecutionContainer {
    ws_url: Url,
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::error::ErrorKind;
    use std::path::PathBuf;

    fn write_temp_nodes_json(contents: &str) -> PathBuf {
        let mut path = std::env::temp_dir();
        let unique = format!(
            "spammer-nodes-{}-{}.json",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .expect("system time after unix epoch")
                .as_nanos()
        );
        path.push(unique);
        std::fs::write(&path, contents).expect("write temp nodes json");
        path
    }

    #[test]
    fn ws_url_from_str_adds_ws_scheme_if_missing() {
        let url = ws_url_from_str("127.0.0.1:8546".to_string());
        assert_eq!(url.as_str(), "ws://127.0.0.1:8546/");
    }

    #[test]
    fn ws_url_from_str_parses_endpoint() {
        let url = ws_url_from_str("ws://127.0.0.1:8546".to_string());
        assert_eq!(url.as_str(), "ws://127.0.0.1:8546/");
    }

    #[test]
    fn ws_urls_from_strings_parses_endpoints() {
        let urls = ws_urls_from_strings(vec![
            "127.0.0.1:8546".to_string(),
            "ws://127.0.0.1:9546".to_string(),
        ]);

        assert_eq!(urls.len(), 2);
        assert_eq!(urls[0].0, "127.0.0.1:8546");
        assert_eq!(urls[0].1.as_str(), "ws://127.0.0.1:8546/");
        assert_eq!(urls[1].0, "ws://127.0.0.1:9546");
        assert_eq!(urls[1].1.as_str(), "ws://127.0.0.1:9546/");
    }

    #[test]
    fn ws_urls_from_file_parses_endpoints() -> Result<()> {
        let nodes_json = r#"
[
  {"name":"validator1","execution":{"ws_url":"ws://127.0.0.1:8546"}},
  {"name":"validator2","execution":{"ws_url":"ws://127.0.0.1:9546"}}
]
"#;
        let path = write_temp_nodes_json(nodes_json);

        // When no names are provided, all nodes from the file are selected.
        let all = ws_urls_from_file(path.to_str().unwrap(), vec![])?;
        let want_nodes = vec![
            (
                "validator1".to_string(),
                Url::parse("ws://127.0.0.1:8546/").unwrap(),
            ),
            (
                "validator2".to_string(),
                Url::parse("ws://127.0.0.1:9546/").unwrap(),
            ),
        ];
        assert_eq!(all, want_nodes);

        // When a subset of names is provided, only those are returned.
        let subset = ws_urls_from_file(path.to_str().unwrap(), vec!["validator2".to_string()])?;
        let want_subset = vec![(
            "validator2".to_string(),
            Url::parse("ws://127.0.0.1:9546/").unwrap(),
        )];
        assert_eq!(subset, want_subset);

        // Unknown names return an error.
        let err = ws_urls_from_file(path.to_str().unwrap(), vec!["does-not-exist".to_string()])
            .unwrap_err();
        assert!(
            err.to_string().contains("Target node not found"),
            "unexpected error: {err:?}"
        );

        let _ = std::fs::remove_file(path);
        Ok(())
    }

    #[test]
    fn cli_parses_ws_subcommand_with_targets_flag() {
        let cli = Cli::try_parse_from([
            "spammer",
            "ws",
            "--targets",
            "127.0.0.1:8546,ws://127.0.0.1:9546",
        ])
        .expect("parsing ws subcommand with --targets");

        match cli.command {
            TargetCommand::Ws { targets } => {
                assert_eq!(
                    targets,
                    Some(vec![
                        "127.0.0.1:8546".to_string(),
                        "ws://127.0.0.1:9546".to_string(),
                    ])
                );
            }
            _ => panic!("expected ws subcommand"),
        }
    }

    #[test]
    fn cli_rejects_ws_positional_targets() {
        let err = match Cli::try_parse_from(["spammer", "ws", "127.0.0.1:8546"]) {
            Ok(_) => panic!("positional ws targets must be rejected"),
            Err(err) => err,
        };

        assert_eq!(err.kind(), ErrorKind::UnknownArgument);
        assert!(err.to_string().contains("127.0.0.1:8546"));
    }

    #[test]
    fn cli_parses_nodes_subcommand_with_targets_flag() {
        let cli = Cli::try_parse_from([
            "spammer",
            "nodes",
            "--nodes-path",
            "nodes.json",
            "--targets",
            "validator1,validator2",
        ])
        .expect("parsing nodes subcommand with --targets");

        match cli.command {
            TargetCommand::Nodes {
                nodes_path,
                targets,
            } => {
                assert_eq!(nodes_path, "nodes.json");
                assert_eq!(
                    targets,
                    Some(vec!["validator1".to_string(), "validator2".to_string()])
                );
            }
            _ => panic!("expected nodes subcommand"),
        }
    }

    #[test]
    fn cli_rejects_nodes_positional_targets() {
        let err = match Cli::try_parse_from([
            "spammer",
            "nodes",
            "--nodes-path",
            "nodes.json",
            "validator1",
        ]) {
            Ok(_) => panic!("positional node targets must be rejected"),
            Err(err) => err,
        };

        assert_eq!(err.kind(), ErrorKind::UnknownArgument);
        assert!(err.to_string().contains("validator1"));
    }

    #[test]
    fn cli_accepts_shared_flags_after_nodes_subcommand() {
        let cli = Cli::try_parse_from([
            "spammer",
            "nodes",
            "--nodes-path",
            "nodes.json",
            "--targets",
            "validator1,validator2",
            "--rate",
            "42",
        ])
        .expect("parsing shared flags after nodes subcommand");
        assert_eq!(cli.args.rate, 42);
    }

    #[test]
    fn cli_parses_fire_and_forget_flag() {
        // Default: fire_and_forget is false (backpressure is the default)
        let cli = Cli::try_parse_from(["spammer", "ws"]).expect("parsing ws subcommand");
        assert!(!cli.fire_and_forget);

        // Explicit: --fire-and-forget
        let cli = Cli::try_parse_from(["spammer", "ws", "--fire-and-forget"])
            .expect("parsing --fire-and-forget");
        assert!(cli.fire_and_forget);

        // Works after subcommand with other flags
        let cli = Cli::try_parse_from([
            "spammer",
            "ws",
            "--targets",
            "127.0.0.1:8546,ws://127.0.0.1:9546",
            "--fire-and-forget",
            "--rate",
            "500",
        ])
        .expect("parsing --fire-and-forget with other flags");
        assert!(cli.fire_and_forget);
        assert_eq!(cli.args.rate, 500);
    }
}
